### ISSUE TITLE
multiple erlapps

### ISSUE THREAD

**Issue by hwinkel** [ShoreTel-Inc/erld#22]
HI,

Can you have multiple erlapps inside one Erlang VM controlled by erld?

**Comment by eproxus** [comment]
You mean Erlang apps? That would be an Erlang release and is totally possible to run in erld, as a release is running inside a VM.

**Comment by hwinkel** [comment]
let try to make it more clear. I have One Erlang VM wich has multiple Erlang Application running in this one VM. Now I want to control this applications from the OS based Init system (scripts, systemd, upstart...) int his scenario I need to address the Application inside the VM rather then having a VM running per application. Is this possible or erld expect a Erlang Release always "packed" with the VM ?

**Comment by eproxus** [comment]
I'd then suggest making one init script for erld + the whole VM and the release of apps (with the appropriate startup instructions for apps, either started or not started). Then, make custom init scripts for each app that talk to the already started erld VM (where you implement [or copy from somewhere] `start`, `stop` and `status` etc. to talk to the Erlang VM remotely).

You could also run one VM per app if that is appropriate for you, but that would be a bigger overhead performance wise (although maybe more resilient, in case one app behaves extremely badly).

**Comment by bernardd** [comment]
As eproxus has implied, erld doesn't really specifically support this per se, but there's nothing to stop you using erld to control the VM and then having a bunch of other init scripts (or a single parameterised one) to control the applications using rpc calls.

**Comment by bernardd** [comment]
I don't think there's much more to be said or done here - closing the issue.
