### ISSUE TITLE
simplify adding erld erlang code to project

### ISSUE THREAD

**Issue by vesperusiak** [ShoreTel-Inc/erld#24]
I suggest to create some submodule named for example erld_erl where will be full erld erlang app which could be easily added into bigger project with erlang.mk or rebar, smth like that:
https://github.com/livechat/erld
Could you do that? It's quite ugly that i had to copy part of your repo to add erld app to project ;(

Btw i'm really grateful to you for creating and opening this soft to the world!

**Comment by bernardd** [comment]
Hi - I'd be quite happy to add something like that; I just don't have the time to do it myself right now. If you'd like to do it and submit a patch that'd be awesome.

Cheers

**Comment by eproxus** [comment]
What is the actual problem with including the app as it is?

**Comment by vesperusiak** [comment]
I had errors when added whole erld repo to project with erlang.mk. The second reason is that erld tool written in c is not part of application that we want to include in release.

**Comment by bernardd** [comment]
Change is merged in - thanks very much for the patch.
